### ISSUE TITLE
The connection to jolokia failed!

### ISSUE THREAD

**Issue by EfraimLA** [fabric8io-images/s2i#238]
I am using fabric8-maven-plugin:4.2.0 and fabric8/s2i-java:2.3 image, also vertx-maven-plugin as generator, and i'm trying to open java console in openshift but cannot connect

Here's my jolokia.properties:
~~~
host=*
port=8778
discoveryEnabled=false
user=jolokia
password=jolokia
useSslClientAuthentication=true
extraClientCheck=true
protocol=https
caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
clientPrincipal=cn=system:master-proxy
~~~

Also i set AB_JOLOKIA_PASSWORD_RANDOM = false

But i get authentication request, tried with the jolokia user and password, openshift user, even with admin but couldn't connect

![Screenshot from 2019-08-30 13-18-22](https://user-images.githubusercontent.com/46459026/64043094-1224a580-cb29-11e9-85fc-82ebb4c73914.png)

**Comment by astefanutti** [comment]
Could you provide more info on your OpenShift cluster?

There is a known issue related to the Jolokia endpoint authentication that affects OpenShift 4, but also Minishift 3.11.

To work-around the issue, you can set `useSslClientAuthentication` to `false`. Otherwise, the new Hawtio console has to be used and configured to use a client certificate as documented here: https://github.com/hawtio/hawtio-online#openshift-4.

**Comment by EfraimLA** [comment]
I noticed about, i'm running minishift 3.11, after googling it more and more i disabled useSslClientAuthentication and worked well, thanks
